backend:
  name: github
  branch: master
  repo: Pierre-Guichard/victor-hugo
  # auth_scope: repo # this is needed to fork the private repo
  open_authoring: true


media_folder: "site/static/img"
public_folder: "img"
publish_mode: editorial_workflow


collections:
  - name: "articles"
    label: "Articles"
    label_singular: "Article"
    folder: "site/content/articles"
    create: true
    fields:
      - name: "title"
        label: "Titre"
        widget: "string"
      - name: "body"
        label: "Contenu"
        widget: "markdown"
      - name: "tags"
        label: "Tags"
        widget: "relation"
        collection: "tags"
        multiple: true
        valueField: "name"
        searchFields: ["name"]
  - name: "tags"
    label: "Tags"
    label_singular: "Tag"
    folder: "site/content/categories"
    create: true
    fields:
      - name: "name"
        label: "Nom"
        widget: "string"